# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sogenactif}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["LIM SAS", "Damien MATHIEU", "Julien SANCHEZ", "Herv\303\251 GAUCHER"]
  s.date = %q{2010-07-01}
  s.description = %q{Need online payment?}
  s.email = %q{damien.mathieu@lim.eu}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/sogenactif.rb",
     "lib/sogenactif/errors.rb",
     "lib/sogenactif/request.rb",
     "lib/sogenactif/request/binary.rb",
     "lib/sogenactif/request/params.rb",
     "lib/sogenactif/response.rb",
     "lib/sogenactif/response/binary.rb",
     "spec/sogenactif/request/binary_spec.rb",
     "spec/sogenactif/request/params_spec.rb",
     "spec/sogenactif/request_spec.rb",
     "spec/sogenactif/response/binary_spec.rb",
     "spec/sogenactif/response_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/LIMSAS/sogenactif}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Process online payments through the Sogenactif gateway}
  s.test_files = [
    "spec/sogenactif/request_spec.rb",
     "spec/sogenactif/response/binary_spec.rb",
     "spec/sogenactif/response_spec.rb",
     "spec/sogenactif/request/params_spec.rb",
     "spec/sogenactif/request/binary_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

